<?php

function boolean_formatter_display_formats(array $options = array()) {
  $formats = array(
    'yes-no' => array(t('Yes'), t('No')),
    'true-false' => array(t('True'), t('False')),
    'on-off' => array(t('On'), t('Off')),
    'enabled-disabled' => array(t('Enabled'), t('Disabled')),
    'boolean' => array(1, 0),
    'unicode-yes-no' => array('✔', '✖'),
    'custom' => array(t('Custom')),
  );
  if (isset($options['custom_on']) && isset($options['custom_off'])) {
    $formats['custom'] = array($options['custom_on'], $options['custom_off']);
  }
  return $formats;
}

function boolean_formatter_display_format_options(array $options = array()) {
  $format_options = array();
  foreach (boolean_formatter_display_formats($options) as $key => $format) {
    $format_options[$key] = implode('/', $format);
  }
  return $format_options;
}

function boolean_formatter_display_value_with_format($value, $format, array $options = array()) {
  $formats = boolean_formatter_display_formats($options);
  if (!isset($formats[$format])) {
    // If format is invalid, default to the first available format.
    reset($formats);
    $format = key($formats);
  }
  if (!empty($options['reverse'])) {
    $value = !(bool) $value;
  }
  // The first format value is the 'On' value, the second is the 'Off' format.
  return !empty($value) ? $formats[$format][0] : $formats[$format][1];
}
